# Generated by Django 4.0.5 on 2022-06-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100000)),
                ('url', models.CharField(max_length=100000)),
                ('image', models.CharField(max_length=100000)),
                ('description', models.CharField(max_length=100000)),
                ('review', models.CharField(max_length=100000)),
                ('aggregateRating', models.CharField(max_length=100000)),
                ('contentRating', models.CharField(max_length=100000)),
                ('datePublished', models.CharField(max_length=100000)),
                ('keywords', models.CharField(max_length=100000)),
                ('actor', models.CharField(max_length=100000)),
                ('director', models.CharField(max_length=100000)),
                ('creator', models.CharField(max_length=100000)),
            ],
        ),
    ]
