# Generated by Django 4.0.5 on 2022-06-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmovie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100000)),
                ('value', models.FloatField()),
            ],
        ),
    ]
