# Generated by Django 4.0.5 on 2022-06-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmovie', '0002_wov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wov',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
